config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
    if @task.completed
      @checkbox_message = "This task is completed"
    else
      @checkbox_message = "This task is not completed yet"
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to @task
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to @task
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<h1>New Task</h1>

  <%= form_for(@task) do |f| %>
    <div class="form-group">
      <%= f.label :title%>
      <%= f.text_field :title%>
    </div>
    <div class="form-group">
      <%= f.label :details%>
      <%= f.text_area :details %>
    </div>
    <% unless @task.new_record? %>
      <div class="form-group">
        <%= f.label :completed%>
        <%= f.check_box :completed %>
      </div>
    <% end %>
  <%= f.submit%>
<% end %>
<%= link_to "Back to list", tasks_path  %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<form action="">
  <% @tasks.each do |task| %>
  <div class="form-group">
    <input type="checkbox" <%= "checked" if task.completed %>>
    <%= link_to task.title,task_path(task)  %>
    <%= link_to "| delete",destroy_path(task), method: :delete, data: { confirm: "Sure?" }  %>
    <!-- <label for=""><%= task.title %></label> -->
  </div>
  <% end %>
</form>

<%= link_to "Add new task", tasks_new_path  %>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<span>
  <%= link_to "Edit this task",  edit_path%>
</span>
<p><%= @task.details %></p>
<form action="">
  <input type="checkbox" <%= "checked" if @task.completed %>><%= @checkbox_message %>
</form>
<%= link_to "Back to list",tasks_path  %>